#### Question 1
What's the version of NumPy that you installed?

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

#### Question 2
What's the version of Pandas?

In [3]:
import pandas as pd

In [4]:
pd.__version__

'1.1.3'

#### Question 3
What's the average price of BMW cars in the dataset?

In [5]:
data_df = pd.read_csv("data.csv")
data_df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [6]:
makegrouping = data_df.groupby('Make')
average_price_of_BMW = makegrouping['Make', 'MSRP'].mean()

average_price_of_BMW.head(9)

<ipython-input-6-cbc4a0c39605>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  average_price_of_BMW = makegrouping['Make', 'MSRP'].mean()


MSRP
Make                      
Acura         3.488759e+04
Alfa Romeo    6.160000e+04
Aston Martin  1.979104e+05
Audi          5.345211e+04
BMW           6.154676e+04
Bentley       2.471693e+05
Bugatti       1.757224e+06
Buick         2.820661e+04
Cadillac      5.623132e+04

In [7]:
print('Average price of BMW', average_price_of_BMW.loc['BMW'])

Average price of BMW MSRP    61546.763473
Name: BMW, dtype: float64


#### Question 4
Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [8]:
cars_2015_df = data_df.loc[data_df['Year'] >= 2015]
print('Missing value for Engine HP in year 2015 = ',cars_2015_df['Engine HP'].isnull().sum())

Missing value for Engine HP in year 2015 =  51


#### Question 5
1. Calculate the average "Engine HP" in the dataset.
2. Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
3. Now, calcualte the average of "Engine HP" again.
4. Has it changed?

In [9]:
#checking engine hp has missing value/not
data_df['Engine HP'].isnull().any()

True

In [24]:
avg_engine_hp_1 = data_df['Engine HP'].mean()
round(avg_engine_hp_1, 2)

249.39

In [25]:
data_df['Engine HP Mean'] = data_df['Engine HP'].fillna(avg_engine_hp_1)

In [26]:
data_df['Engine HP Mean'].isnull().any()

False

In [27]:
avg_engine_hp_2 = data_df['Engine HP Mean'].mean()
round(avg_engine_hp_2, 2)

249.39

#### Question 6
1. Select all the "Rolls-Royce" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. What's the sum of all the elements of the result?  

Hint: if the result is negative, re-read the task one more time

In [34]:
make_rolls_royce = data_df.loc[data_df['Make']=='Rolls-Royce']
select_col = make_rolls_royce[['Engine HP', 'Engine Cylinders', 'highway MPG']]

select_col

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [35]:
select_col.drop_duplicates(inplace=True)

<ipython-input-35-2edba78d56da>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  select_col.drop_duplicates(inplace=True)


In [36]:
select_col.shape

(7, 3)

In [39]:
X = select_col.to_numpy()
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [47]:
XTX = np.dot(X.T, X)

XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [48]:
invert_xtx = np.linalg.inv(XTX)

invert_xtx

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [49]:
sum_of_all_the_elements = invert_xtx.sum()

sum_of_all_the_elements

0.032212320677486195

#### Questions 7
1. Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
2. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.  

What's the value of the first element of w?.

In [50]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [81]:
w = np.dot(invert_xtx, X.T)
w = np.dot(w,y)

w

array([ 0.19989598, 31.02612262, 31.65378877])